name: sync-faker2fok # 名称随意
on: 
  schedule: 
  - cron: '0 0 * * *'
  workflow_dispatch: 
  watch: 
   types: started 
  repository_dispatch:
    types: sync-faker2fok # 上面名字改了这也要改
jobs: 
 repo-sync: 
     env: 
       PAT: ${{ secrets.PAT }} 
     runs-on: ubuntu-latest 
     if: github.event.repository.owner.id == github.event.sender.id 
     steps: 
      - uses: actions/checkout@v2 
        with: 
          persist-credentials: false 
    
      - name: sync faker2fok # 上面名字改了这也要改
        uses: repo-sync/github-sync@v2 
        if: env.PAT 
        with: 
          source_repo: "https://github.com/shufflewzc/faker2.git" # 上游仓库地址
          source_branch: "main" 
          destination_branch: "master" # 按照自己仓库分支名称修改
          github_token: ${{ secrets.PAT }} 
